#!/bin/bash

set -euo pipefail

function usage {
    echo "To create a new project, first create a branch with a name that starts with 'project/'."
    echo "Then run this script with the name of the starter kit you want to use for the project."
    echo "For example:"
    echo ""
    echo "  $0 simple-animation"
    echo ""
    exit 1
}

if (($# < 1)); then usage; fi

kit="$1"

dir=$(git branch --show-current)

if [ "${dir:0:8}" != "project/" ]; then
    echo "Must be on a project/* branch to start a project."
    exit 1
fi

if [ -e "$dir" ]; then
    echo "$dir already exists!"
    exit 1
fi

tmp=$(mktemp)
mkdir -p "$dir"
cd "$dir"
curl --fail "https://intro.gigamonkeys.com/starter-kits/$kit.tgz" > "$tmp"
cat "$tmp" | tar xzf -
npm install
