#!/bin/bash

set -euo pipefail

function usage {
    echo "usage: $0 PROJECT_NAME KIT_NAME"
    exit 1
}

if (($# < 2)); then usage; fi

name="$1"
kit="$2"

dir="project/$name"

if [ -e "$dir" ]; then
    echo "$dir already exists!"
    exit 1
fi

tmp=$(mktemp)
mkdir -p "$dir"
cd "$dir"
curl --fail "https://intro.gigamonkeys.com/starter-kits/$kit.tgz" > "$tmp"
cat "$tmp" | tar xzf -
npm install
